name: recommender_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.2.0
  cloud_firestore: ^4.0.5
  firebase_storage: ^11.0.5
  url_launcher: ^6.1.7
  cached_network_image: ^3.2.3
  hexcolor: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/animation/

  fonts:
    - family: Koruri
      fonts:
        - asset: fonts/Koruri-Bold.ttf
          weight: 700
        - asset: fonts/Koruri-Regular.ttf
          weight: 400
        - asset: fonts/Koruri-Semibold.ttf
          weight: 500
