// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg_fYeUPsqDeRMtqfQrOQIRAEC43EFhoo',
    appId: '1:157467562472:web:0649da1b41e5d6dd7e545d',
    messagingSenderId: '157467562472',
    projectId: 'recommender-11c56',
    authDomain: 'recommender-11c56.firebaseapp.com',
    storageBucket: 'recommender-11c56.appspot.com',
    measurementId: 'G-LMEHR0ZXF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXr9Cr02lSjZN2QyGGaAXrp8WBrE2dyIg',
    appId: '1:157467562472:android:32a4b99450c04f367e545d',
    messagingSenderId: '157467562472',
    projectId: 'recommender-11c56',
    storageBucket: 'recommender-11c56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3DPFY9mV2_m87kWoJTiVqZjxhdNCh-JY',
    appId: '1:157467562472:ios:fe4d1ee7be2befba7e545d',
    messagingSenderId: '157467562472',
    projectId: 'recommender-11c56',
    storageBucket: 'recommender-11c56.appspot.com',
    iosClientId: '157467562472-hs3v0a778t24sp5frsr70qtch34ju8ij.apps.googleusercontent.com',
    iosBundleId: 'com.example.recommenderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3DPFY9mV2_m87kWoJTiVqZjxhdNCh-JY',
    appId: '1:157467562472:ios:e835a44762097d247e545d',
    messagingSenderId: '157467562472',
    projectId: 'recommender-11c56',
    storageBucket: 'recommender-11c56.appspot.com',
    iosClientId: '157467562472-6pkamqb3f63gk3rqi5pgmp7aihgof18e.apps.googleusercontent.com',
    iosBundleId: 'c',
  );
}
